In [2]:
"""Write a Python program to create a contiguous flattened array. 
Original array:
[[10 20 30] 
[20 40 50]] 
New flattened array: 
[10 20 30 20 40 50]

"""

import numpy as np

array=[10,20,30]
array1=[20,40,50]

val=np.append(array,array1)
print(sorted(val))
print(np.ravel(val))


[10, 20, 20, 30, 40, 50]
[10 20 30 20 40 50]
