In [14]:
"""Write a Python program to change the data type of an array. 
Expected Output:
[[ 2 4 6]
[ 6 8 10]] 
Data type of the array x is: int32 
New Type: float64 
[[ 2. 4. 6.] 
[ 6. 8. 10.]]
"""

import numpy as np

array=np.array([2,4,6,6,8,10],dtype=int).reshape(2,3)
print((array))
array1=np.array([2,4,6,6,8,10],dtype=float).reshape(2,3)
print((array1))

[[ 2  4  6]
 [ 6  8 10]]
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [17]:
arr=np.array([[2,4,6],[6,8,10]],np.int32)
print(arr,arr.dtype)
arr1=arr.astype(f)

[[ 2  4  6]
 [ 6  8 10]] int32
