In [5]:
'''Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere. 
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.] 
[ 0. 0. 1.]]'''

import numpy as np

arr=np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
for col in range(3):
    for row in range(3):
        if(col==row):
            print(1.,end=" ")
        else:
            print(0.,end=" ")
    print("")

1.0 0.0 0.0 
0.0 1.0 0.0 
0.0 0.0 1.0 
