In [31]:
'''Write a Python program to create an array which looks like below array. 
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]
'''
import numpy as np

arr=np.zeros((4,3))
arr[3:,:3]=1
arr[2:,:2]=1
arr[1:,:1]=1

print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [30]:
arr=np.zeros((4,3))
for i in range(0,3):
    arr[i+1:,:i+1]=1
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
