In [9]:
'''Write a Python program to remove specific elements in a numpy array. 

Expected Output:
Original array: 
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]
'''

import numpy as np

arr=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(arr)

print(np.delete(arr,[0,3,4]))

[ 10  20  30  40  50  60  70  80  90 100]
[ 20  30  60  70  80  90 100]


[ 10  20  30  40  50  60  70  80  90 100]
[ 20  30  40  50  60  70  80  90 100]
