In [6]:
# Write a Python program to convert a list and tuple into arrays. 
'''List to array:
[1 2 3 4 5 6 7 8] 
Tuple to array:
[[8 4 6] 
[1 2 3]]'''

import numpy as np 

listValue=[1,2,3,4,5,6,7,8]
listCarray=np.array(listValue)
print(listCarray)
tupleValue=(8,4,6,1,2,3)
tupleCarray=np.array(tupleValue).reshape(2,3)
print(tupleCarray)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]
