In [6]:
# 9 Write a Python program to append values to the end of an array. 
"""Expected Output:
Original array:
[10, 20, 30] 
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]"""

import numpy as np

listValues=[10,20,30]
array=np.array(listValues)
print(array)
listvalues2=np.append(listValues,[40,50,60,70,80,90])
print(listvalues2)




[10 20 30]
[10 20 30 40 50 60 70 80 90]


In [7]:
listval=[40,50,60,70,80,90]
appendvalu=np.append(listValues,listval)
print(app)